/** @type {import('tailwindcss').Config} */
// const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },

    extend: {
      colors: {
        fxDarkSocials: "hsl(193, 15%, 30%)",
        fxRealDarkGray: "hsl(192, 22%, 51%)",
        fxDarkTextBlue: "hsl(252, 35%, 19%)",
        portfolioWhiteBg: "hsl(0, 0%, 100%)",
        portfolioGrayBg: "hsl(0, 0%, 97%)",
        portfolioGreenBg: "hsl(158, 100%, 33%)",
        portfolioNavText: "hsl(240, 10%, 4%)",
        portfolioBlue: "hsl(198, 76%, 47%)",
        portfolioBlueHover: "hsl(198, 76%, 55%)",
        portfolioTitle: "hsl(90, 10%, 4%)",
        portfolioTextP: "hsl(0, 0%, 25%)",
        portfolioSectionTitle1: "hsl(192, 24%, 96%)",
        portfolioGrayText: "hsl(60, 0%, 42%)",
        portfolioGrayDarkBg: "hsl(0, 0%, 39%)",
        portfolioGrayDarkBg100: "hsl(0, 0%, 60%)",
        portfolioGrayDarkBg200: "hsl(0, 0%, 85%)",
        portfolioLineColor: "hsl(0, 0%, 93%)",
        portfolioFooterBg: "hsl(208, 34%, 20%)",
        portfolioFooterTextColor: "hsl(208, 28%, 78%)",
        portfolioFooterTextColorHover: "hsl(146, 50%, 81%)",
        portfolioGreenText: "hsl(167, 92%, 29%)",
        portfolioPrimaryText: "hsl(220, 54%, 20%)",
        portfolioSecondaryText: "hsl(220, 30%, 39%)",
        portfolioBlueText: "hsl(215, 91%, 50%)",
        portfolioBlueTextHover: "hsl(214, 87%, 40%)",
        portfolioBlueBackGroundColor: "hsl(210, 75%, 97%)",
        // portfolioLigthBlueBackGroundColor: "hsl(209, 87%, 94%)",
        portfolioLigthBlueBackGroundColor: "hsl(210, 100%, 91%)",
        portfolioLigthBlueBackGroundHoverColor: "hsl(209, 87%, 94%)",
        portfolioNavColor: "hsl(220, 30%, 39%)",
        portfolioNavBgColor: "hsl(214, 32%, 91%)",
        // portfolioNavColorHover: "hsl(220, 30%, 50%)",
        portfolioNavColorHover: "hsl(221, 25%, 60%)",
        portfolioBackgroundCard: "hsl(205, 100%, 94%)",
        portfolioTextcolorCard: "hsl(214, 94%, 43%)",
        portfolioMenuColor: "hsl(166, 81%, 96%)",
      },
      fontFamily: {
        sans: ["Josefin Sans", "sans-serif"],
        jamjuree: ["Bai Jamjuree", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        lato: ["Lato", "sans-serif"],
        nunito: ["Nunito Sans", "sans-serif"],
      },
      backgroundImage: (theme) => ({
        "logo-dark-mode": "url('../img/logo-dark-mode.png')",
        "logo-light-mode": "url('../img/logo-light-mode10.png')",
        "curvy-dark-mode": "url('../img/bg-curvy-dark-mode.svg')",
        "curvy-light-mode": "url('../img/bg-curvy-light-mode.svg')",
      }),
    },
  },
  variants: {
    extend: {
      backgroundImage: ["dark"],
    },
  },
  plugins: [],
};
